FROM node:alpine AS build
WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . .

ARG NEXT_PUBLIC_API_GRAPHQL \
  NEXT_PUBLIC_FIREBASE_API_KEY \
  NEXT_PUBLIC_FIREBASE_APP_ID \
  NEXT_PUBLIC_FIREBASE_PROJECT_ID \
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
  I18NEXUS_API_KEY

ENV NEXT_PUBLIC_API_GRAPHQL $NEXT_PUBLIC_API_GRAPHQL \
  NEXT_PUBLIC_FIREBASE_API_KEY $NEXT_PUBLIC_FIREBASE_API_KEY \
  NEXT_PUBLIC_FIREBASE_APP_ID $NEXT_PUBLIC_FIREBASE_APP_ID \
  NEXT_PUBLIC_FIREBASE_PROJECT_ID $NEXT_PUBLIC_FIREBASE_PROJECT_ID \
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN $NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET $NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID $NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID $NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
  I18NEXUS_API_KEY $I18NEXUS_API_KEY

RUN yarn run build

FROM node:alpine AS runner
WORKDIR /app
COPY --from=build /app /app
EXPOSE 3000
CMD ["yarn", "run", "start"]