version: '3'
services:
  app:
    container_name: oas-platform-hotels-master-frontend
    build:
      context: ./
      args:
        NEXT_PUBLIC_API_GRAPHQL: https://api.smartgo.life/graphql
        NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyCZxy_LNGr7dn17eiXlaBRYT4TdrU_V2JI
        NEXT_PUBLIC_FIREBASE_APP_ID: 1:261377799143:web:4319e57b8e5df301f20342
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: oas-platform
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: oas-platform.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: oas-platform.appspot.com
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-5EG5H7WB2H
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 261377799143
        I18NEXUS_API_KEY: ROJ9P6fy2ajjzBJRhwBsvg
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3000:3000'
